### ISSUE TITLE
Needs climate library error message

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-Dynamic-Fire-System#2]
When you run DFFS and specify a climate input file that doesn't exist in the directory, it assumes there is no climate data and doesn't generate ANY fires.  It should trigger an error.

**Comment by bmarron18** [comment]
First round QAQC a no-go:

Internal error occurred within the program: Object reference not set to an instance of an object.

Stack trace: at Landis.Library.Metadata.DataTableExtensions.SetColumns[T](DataTable tbl)
at Landis.Library.Metadata.MetadataTable`1..ctor(String filePath)
at Landis.Extension.DynamicFire.MetadataHandler.InitializeMetadata(String mapNameTemplate, String eventLogName, String summaryLogName)
at Landis.Extension.DynamicFire.PlugIn.Initialize()
at Landis.Model.InitExtensions(ExtensionMain[] extensions)
at Landis.Model.Run(String scenarioPath, IUserInterface ui)
at Landis.App.Main(String[] args)

**Comment by rmscheller** [comment]
Bruce, this message is triggered by Metadata, belongs in that issue.

**Comment by bmarron18** [comment]
Yes, thanks. Added the QAQC Metadata results to both this repo as well as the Dynamic Fuels repo because they are linked.
